### PR TITLE
Remove incorrect entries

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by orbitcowboy** [comment]
Thanks!

**Comment by luzpaz** [comment]
PR was reverted in e8f2ecd3c8602f3674b29a2681455ff5ad0372c9 any idea why ?

**Comment by luzpaz** [comment]
@orbitcowboy :point_up:

**Comment by orbitcowboy** [comment]
Your changes have been integrated again with https://github.com/orbitcowboy/codespell_dictionary/commit/ae35047a9806c929df188e3f4f91701aefd21f75

**Comment by luzpaz** [comment]
thx

**Pull request merged**
